-- Get all the Movies List 

USE MAVENMOVIES;

SELECT * FROM RENTAL;

SELECT * FROM FILM;

SELECT * FROM INVENTORY;

SELECT * FROM PAYMENT;

SELECT * FROM CUSTOMER;

SELECT * FROM ADDRESS;

SELECT * FROM CITY;

SELECT * FROM COUNTRY;

SELECT * FROM LANGUAGE;

SELECT * FROM CATEGORY;

SELECT * FROM FILM_CATEGORY;

SELECT * FROM ACTOR;

SELECT * FROM FILM_ACTOR;

-- GET THE LIST OF CUSTOMERS AND THEIR EMAIL IDS

SELECT EMAIL,FIRST_NAME,LAST_NAME
FROM CUSTOMER;

-- GET THE LIST OF FIRST 10 CUSTOMERS AND THEIR EMAIL IDS

SELECT CUSTOMER_ID,EMAIL,FIRST_NAME,LAST_NAME
FROM CUSTOMER
LIMIT 10 OFFSET 2;

-- Total revenuve and total transaction 

SELECT SUM(AMOUNT) AS REVENUE 
FROM PAYMENT;

SELECT COUNT(AMOUNT) AS REVENUE 
FROM PAYMENT; 

SELECT COUNT(*) AS TOTAL_TRANS
FROM CUSTOMER;

SELECT *
FROM ADDRESS;

SELECT AVG(AMOUNT) AS AOV
FROM PAYMENT; 


SELECT *,CONCAT(FIRST_NAME," ",LAST_NAME) AS FULL_NAME 
FROM CUSTOMER;

SELECT *,LOWER(FIRST_NAME),UPPER(EMAIL)
FROM CUSTOMER;

SELECT *,CONCAT(FIRST_NAME," ",SUBSTR(LAST_NAME,1,3)) AS USER_NAME 
FROM CUSTOMER;

-- FILTARING RENTAL TABLE AS PER CUSTOMER

SELECT*
FROM RENTAL
WHERE CUSTOMER_ID <>7;

SELECT *
FROM RENTAL
ORDER BY CUSTOMER_ID ASC;

SELECT *
FROM RENTAL
ORDER BY CUSTOMER_ID DESC;

SELECT * 
FROM CUSTOMER
WHERE CUSTOMER_ID BETWEEN 3 AND 8;


SELECT * 
FROM CUSTOMER
WHERE CUSTOMER_ID <=4 AND COSTOMER_ID >=7;

SELECT * 
FROM CUSTOMER
WHERE CUSTOMER_ID =1 OR CUSTOMER_ID=3 OR CUSTOMER_ID = 5;

SELECT * 
FROM CUSTOMER
WHERE CUSTOMER_ID IN (1,3,5,6,7); 

-- PRINT A REPORT OF EVERYTING THE CUSTOMER_ID 4 HAS EVER PURCHASESD AT THE SORTE AND SORT THIS DATA BY DATA 

SELECT *
FROM RENTAL
WHERE CUSTOMER_ID =4
ORDER BY RENTAL_DATE DESC;










